### ISSUE TITLE
ID Conflict

### ISSUE THREAD

**Issue by Matmatix** [Matmatix/clientside-files#5]
Random structure in worldgen created with Compact Machine Walls from Compact Machines 2 and a pink liquid.
![2018-02-26_00 04 26](https://user-images.githubusercontent.com/17185521/36655503-ab5d1690-1a88-11e8-8e48-81c148cadb9c.png)

**Comment by jwf1112** [comment]
pink liquid from structure causes shrinking 2, which makes you about the size of one block so from this would appear that the random structure is a compact machine which failed and expanded/broke (so a legitimate structure from world gen) pink liquid could possibly be required for compact machines (have not tried making one so am not sure)
